# general
install cmake
install git

# editor
install macvim --override-system=vim

# the silver searcher
install ag

# ruby
install rbenv
install ruby-build
install rbenv-gemset --HEAD
install rbenv-gem-rehash

# pow
# install pow (uncomment if new version comes out, currently 0.4.1 which has issues with rbenv)

# tmux
install tmux
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
install reattach-to-user-namespace

# cask
cask install alfred
cask install virtualbox
cask install vagrant
cask install slate

# Finally link the apps
linkapps
