#!/usr/bin/env ruby

require 'pathname'
require 'fileutils'

DOTFILES = File.join(File.dirname(Pathname.new(__FILE__).realpath))
HOME = ENV['HOME']

Dir.chdir(DOTFILES)

def status(s)
  puts [s ? "\e[92m" : "\e[31", s, "\e[0m"].join
end

# Symlink *.symlink files
Dir.glob(['**/*.symlink', '**/*.dsymlink']).each do |f|
  dir, base = Pathname.new(f).split
  name_without_symlink = base.basename('.*')
  if base.extname == '.dsymlink'
    # symlink in hidden directory
    fulldir = File.join(HOME, ".#{dir}")
    FileUtils.mkdir_p fulldir
    dst = File.join(fulldir, name_without_symlink)
  else
    # symlink for hidden file
    dst = File.join(HOME, ".#{name_without_symlink}")
  end

  src = File.join(DOTFILES, f)
  puts "Symlink #{dst}"
  FileUtils.ln_sf(src, dst)
end
