#!/usr/bin/env ruby

require 'pathname'
require 'fileutils'

DOTFILES = File.join(File.dirname(Pathname.new(__FILE__).realpath))
HOME = ENV['HOME']

Dir.chdir(DOTFILES)

def status(s)
  puts [s ? "\e[92m" : "\e[31", s, "\e[0m"].join
end

# Symlink *.symlink files
Dir.glob('**/*.symlink').each do |f|
  _, base = Pathname.new(f).split
  filename = ".#{base.basename('.*')}"
  # rel_dir = dir.each_filename.to_a[1..-1]

  src = File.join(DOTFILES, f)
  dst = File.join(HOME, filename)
  puts "Symlink #{dst}"
  FileUtils.ln_sf(src, dst)
end
